
package it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMessaggisticaWS", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/")
public interface IMessaggisticaWS
{

  /**
   * 
   * @param idAllegato
   * @return returns byte[]
   * @throws InternalException_Exception
   */
  @WebMethod
  @WebResult(name = "allegato", targetNamespace = "")
  @RequestWrapper(localName = "getAllegato", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetAllegato")
  @ResponseWrapper(localName = "getAllegatoResponse", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetAllegatoResponse")
  public byte[] getAllegato(
      @WebParam(name = "idAllegato", targetNamespace = "") long idAllegato)
      throws InternalException_Exception;

  /**
   * 
   * @param idElencoMessaggi
   * @param codiceFiscale
   * @return returns
   *         it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.DettagliMessaggio
   * @throws InternalException_Exception
   */
  @WebMethod
  @WebResult(name = "dettagliMessaggio", targetNamespace = "")
  @RequestWrapper(localName = "getDettagliMessaggio", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetDettagliMessaggio")
  @ResponseWrapper(localName = "getDettagliMessaggioResponse", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetDettagliMessaggioResponse")
  public DettagliMessaggio getDettagliMessaggio(
      @WebParam(name = "idElencoMessaggi", targetNamespace = "") long idElencoMessaggi,
      @WebParam(name = "codiceFiscale", targetNamespace = "") String codiceFiscale)
      throws InternalException_Exception;

  /**
   * 
   * @param idElencoMessaggi
   * @param codiceFiscale
   * @throws InternalException_Exception
   */
  @WebMethod
  @RequestWrapper(localName = "confermaLetturaMessaggio", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.ConfermaLetturaMessaggio")
  @ResponseWrapper(localName = "confermaLetturaMessaggioResponse", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.ConfermaLetturaMessaggioResponse")
  public void confermaLetturaMessaggio(
      @WebParam(name = "idElencoMessaggi", targetNamespace = "") long idElencoMessaggi,
      @WebParam(name = "codiceFiscale", targetNamespace = "") String codiceFiscale)
      throws InternalException_Exception;

  /**
   * 
   * @param codiceRuolo
   * @param tipoMessaggio
   * @param visibile
   * @param letto
   * @param idProcedimento
   * @param codiceFiscale
   * @param obbligatorio
   * @return returns
   *         it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.ListaMessaggi
   * @throws InternalException_Exception
   * @throws LogoutException_Exception
   */
  @WebMethod
  @WebResult(name = "listaMessaggi", targetNamespace = "")
  @RequestWrapper(localName = "getListaMessaggi", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetListaMessaggi")
  @ResponseWrapper(localName = "getListaMessaggiResponse", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.GetListaMessaggiResponse")
  public ListaMessaggi getListaMessaggi(
      @WebParam(name = "idProcedimento", targetNamespace = "") int idProcedimento,
      @WebParam(name = "codiceRuolo", targetNamespace = "") String codiceRuolo,
      @WebParam(name = "codiceFiscale", targetNamespace = "") String codiceFiscale,
      @WebParam(name = "tipoMessaggio", targetNamespace = "") int tipoMessaggio,
      @WebParam(name = "letto", targetNamespace = "") Boolean letto,
      @WebParam(name = "obbligatorio", targetNamespace = "") Boolean obbligatorio,
      @WebParam(name = "visibile", targetNamespace = "") Boolean visibile)
      throws InternalException_Exception, LogoutException_Exception;

  /**
   * 
   * @param arg1
   * @param arg0
   * @throws LogoutException_Exception
   * @throws InternalException_Exception
   */
  @WebMethod
  @RequestWrapper(localName = "verificaLogout", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.VerificaLogout")
  @ResponseWrapper(localName = "verificaLogoutResponse", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", className = "it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.VerificaLogoutResponse")
  public void verificaLogout(
      @WebParam(name = "arg0", targetNamespace = "") int arg0,
      @WebParam(name = "arg1", targetNamespace = "") String arg1)
      throws InternalException_Exception, LogoutException_Exception;

}
