
package it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@SuppressWarnings("serial")
@WebFault(name = "InternalException", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/")
public class InternalException_Exception
    extends Exception
{

  /**
   * Java type that goes as soapenv:Fault detail element.
   * 
   */
  private InternalException faultInfo;

  /**
   * 
   * @param faultInfo
   * @param message
   */
  public InternalException_Exception(String message,
      InternalException faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  /**
   * 
   * @param faultInfo
   * @param cause
   * @param message
   */
  public InternalException_Exception(String message,
      InternalException faultInfo, Throwable cause)
  {
    super(message, cause);
    this.faultInfo = faultInfo;
  }

  /**
   * 
   * @return returns fault bean:
   *         it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica.InternalException
   */
  public InternalException getFaultInfo()
  {
    return faultInfo;
  }

}
