
package it.csi.nembo.nemboconf.integration.ws.papuaserv.messaggistica;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "messaggistica", targetNamespace = "http://papuaserv.webservice.business.papuaserv.papua.csi.it/", wsdlLocation = "TOBECONFIG/papuaserv/ws/messaggistica?wsdl")
public class Messaggistica
    extends Service
{

  private final static URL                 MESSAGGISTICA_WSDL_LOCATION;
  private final static WebServiceException MESSAGGISTICA_EXCEPTION;
  private final static QName               MESSAGGISTICA_QNAME = new QName(
      "http://papuaserv.webservice.business.papuaserv.papua.csi.it/",
      "messaggistica");

  static
  {
    URL url = null;
    WebServiceException e = null;
    try
    {
      url = new URL(
          "http://TOBECONFIG/papuaserv/ws/messaggistica?wsdl");
    }
    catch (MalformedURLException ex)
    {
      e = new WebServiceException(ex);
    }
    MESSAGGISTICA_WSDL_LOCATION = url;
    MESSAGGISTICA_EXCEPTION = e;
  }

  public Messaggistica()
  {
    super(__getWsdlLocation(), MESSAGGISTICA_QNAME);
  }

  public Messaggistica(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  /**
   * 
   * @return returns IMessaggisticaWS
   */
  @WebEndpoint(name = "messaggisticaPort")
  public IMessaggisticaWS getMessaggisticaPort()
  {
    return super.getPort(new QName(
        "http://papuaserv.webservice.business.papuaserv.papua.csi.it/",
        "messaggisticaPort"), IMessaggisticaWS.class);
  }

  private static URL __getWsdlLocation()
  {
    if (MESSAGGISTICA_EXCEPTION != null)
    {
      throw MESSAGGISTICA_EXCEPTION;
    }
    return MESSAGGISTICA_WSDL_LOCATION;
  }

}
