
package it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2019-01-28T13:31:37.940+01:00
 * Generated source version: 2.4.9
 */

@WebFault(name = "Exception", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/")
public class Exception_Exception extends java.lang.Exception {
    
    private it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.Exception getFaultInfo() {
        return this.exception;
    }
}
