
package it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2019-01-28T13:31:37.944+01:00
 * Generated source version: 2.4.9
 */

@WebFault(name = "ProtocolloInformaticoException", targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/")
public class ProtocolloInformaticoException_Exception extends java.lang.Exception {
    
    private it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloInformaticoException protocolloInformaticoException;

    public ProtocolloInformaticoException_Exception() {
        super();
    }
    
    public ProtocolloInformaticoException_Exception(String message) {
        super(message);
    }
    
    public ProtocolloInformaticoException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ProtocolloInformaticoException_Exception(String message, it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloInformaticoException protocolloInformaticoException) {
        super(message);
        this.protocolloInformaticoException = protocolloInformaticoException;
    }

    public ProtocolloInformaticoException_Exception(String message, it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloInformaticoException protocolloInformaticoException, Throwable cause) {
        super(message, cause);
        this.protocolloInformaticoException = protocolloInformaticoException;
    }

    public it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloInformaticoException getFaultInfo() {
        return this.protocolloInformaticoException;
    }
}
