
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo;

import javax.xml.namespace.QName;

import org.apache.log4j.Logger;

import it.csi.nembo.nembopratiche.util.NemboConstants;


/**
 * This class was generated by Apache CXF 2.4.9
 * 2018-12-10T11:18:22.581+01:00
 * Generated source version: 2.4.9
 * 
 */

@javax.jws.WebService(
                      serviceName = "ServiceProtocolloInformaticoservImplService",
                      portName = "ServiceProtocolloInformaticoservImplPort",
                      targetNamespace = "http://service.gaaserv.agricoltura.aizoon.it/",
                      endpointInterface = "it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv")
                      
public class ServiceProtocolloInformaticoservImpl implements ServiceProtocolloInformaticoserv {    	

	private static final QName SERVICE_NAME = new QName("http://service.gaaserv.agricoltura.aizoon.it/", "ServiceProtocolloInformaticoservImplService");	
	protected static final Logger logger = Logger.getLogger(NemboConstants.LOGGIN.LOGGER_NAME + ".presentation");
    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#isAlive(*
     */
    public boolean isAlive() throws Exception_Exception    { 
        logger.info("BEGIN isAlive");
        try {
        	/*
        	 * ServiceGaaservImplService ss = new ServiceGaaservImplService();
			   portStub = ss.getServiceGaaservImplPort();
        	 */
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.isAlive();
        } 
        catch (java.lang.Exception ex) {
        	logger.error("-- Exception in ServiceProtocolloInformaticoservImpl.isAlive "+ex.getMessage());
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        finally{
          logger.info("END isAlive");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#getDocument(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.DocumentoRefVO  arg0 )*
     */
    public it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.GetDocumentResponseVO getDocument(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.GetDocumentRequestVO arg0) throws Exception_Exception    {  
    	logger.info("BEGIN getDocument");        
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.getDocument(arg0);
        } 
        catch (java.lang.Exception ex) {
        	logger.error( "Eccezione in getDocument ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END getDocument");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#getByNumeroProtocollo(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.NumeroProtocolloVO  arg0 )*
     */
    public it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloResponseVO getByNumeroProtocollo(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.NumeroProtocolloRequestVO arg0) throws Exception_Exception    { 
    	logger.info("BEGIN getByNumeroProtocollo");         
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.getByNumeroProtocollo(arg0);
        } catch (java.lang.Exception ex) {
        	logger.error( "Eccezione in getByNumeroProtocollo ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END getByNumeroProtocollo");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#testResources(*
     */
    public boolean testResources() throws Exception_Exception    { 
    	logger.info("BEGIN testResources");  
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort();
            return port.testResources();
        } catch (java.lang.Exception ex) {
        	logger.error( "Eccezione in testResources ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END testResources");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#insertProtocollo(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.InsertProtocolloRequestVO  arg0 )*
     */
    public it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ProtocolloResponseVO insertProtocollo(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.InsertProtocolloRequestVO arg0) throws ProtocolloInformaticoException_Exception    {   
    	logger.info("BEGIN insertProtocollo");          
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.insertProtocollo(arg0);
        } catch (java.lang.Exception ex) {
        	logger.error( "Eccezione in testResources ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END insertProtocollo");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#addAllegati(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.AddAllegatiRequestVO  arg0 )*
     */
    public int addAllegati(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.AddAllegatiRequestVO arg0) throws Exception_Exception    { 
    	logger.info("BEGIN addAllegati");         
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.addAllegati(arg0);
        } catch (java.lang.Exception ex) {
        	logger.error( "Eccezione in testResources ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END addAllegati");
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.ServiceProtocolloInformaticoserv#notificaByPec(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.NotificaByPecRequestVO  arg0 )*
     */
    public boolean notificaByPec(it.csi.nembo.nembopratiche.integration.ws.gaaserv.protocollo.NotificaByPecRequestVO arg0) throws Exception_Exception    { 
    	logger.info("BEGIN notificaByPec");      
        try {
        	ServiceProtocolloInformaticoservImplService ss = new ServiceProtocolloInformaticoservImplService(ServiceProtocolloInformaticoservImplService.WSDL_LOCATION, ServiceProtocolloInformaticoservImplService.SERVICE);
            ServiceProtocolloInformaticoserv port = ss.getServiceProtocolloInformaticoservImplPort(); 
            return port.notificaByPec(arg0);            
        } catch (java.lang.Exception ex) {
        	logger.error("Eccezione in testResources ="+ex.getMessage(), ex);
            throw new RuntimeException(ex);
        }
        finally{
            logger.info("END notificaByPec");
        }
        //throw new Exception_Exception("Exception...");
    }

}
